[tool.poetry]
name = "fragmenty"
version = "0.1.0"
description = ""
authors = ["Ehsan Titish <Maders@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
